import { PAIR_PACKS } from "./fallbackTerms";

/** Everything the hub, the home-page section and the intro screens need to know about each game. */
export const CATEGORIES = [
  { id: "speed", title: "Speed & Focus", blurb: "Exam pressure, arcade style" },
  { id: "board", title: "Progression & Board", blurb: "Turn the syllabus into a journey" },
  { id: "word", title: "Word & Language", blurb: "Vocabulary, definitions and recall" },
  { id: "social", title: "Social & Competitive", blurb: "Race your class, spend your coins" },
];

export const GAMES = [
  {
    id: "crossword",
    category: "word",
    data: "terms",
    featured: true,
    title: "Crossword",
    tagline: "Clues from real mock-test questions. Fill the grid!",
    emoji: "🧩",
    theme: "crossword",
    glyphs: ["A", "E", "R", "S", "T", "N", "O", "?", "7", "▮"],
    howTo: [
      "Tap a square in the grid, or tap a clue in the list.",
      "Type the answer. The cursor moves to the next square by itself.",
      "Tap the same square again (or press Space) to switch between Across and Down.",
      "Use the arrow keys to move around, Backspace to erase.",
      "Press Check to see which letters are right. Press Finish when you are done.",
    ],
    rules: [
      "Every clue is a question taken from a SetuLearn mock test - the answer is its correct option.",
      "Each correct letter scores 10 points.",
      "Hint (reveal a letter) costs 15 points, Reveal word costs 5 points per letter.",
      "Finishing the whole grid earns a speed bonus.",
    ],
    difficulty: {
      easy: { label: "Easy", note: "6 words", words: 6, size: 13 },
      medium: { label: "Medium", note: "9 words", words: 9, size: 15 },
      hard: { label: "Hard", note: "12 words", words: 12, size: 17 },
    },
  },
  {
    id: "wordsearch",
    category: "word",
    data: "terms",
    featured: false,
    title: "Word Search",
    tagline: "Hunt hidden terms in a sea of letters.",
    emoji: "🔍",
    theme: "wordsearch",
    glyphs: ["~", "°", "○", "A", "S", "W", "≈", "◌"],
    howTo: [
      "Look at the word list. Every word is hidden somewhere in the grid.",
      "Press on the first letter, drag in a straight line to the last letter, then let go.",
      "Words can run across, down and diagonally - on Hard they can also run backwards.",
      "A found word gets coloured and ticked off the list.",
      "Stuck? Use Hint to flash the first letter of a word.",
    ],
    rules: [
      "Each word found scores 100 points, plus a bonus for speed.",
      "A hint costs 40 points.",
      "On Hard the list shows only the CLUE (the mock-test question) - you must work out the word yourself.",
      "Find every word to finish the round.",
    ],
    difficulty: {
      easy: { label: "Easy", note: "8x8 · words shown", size: 8, words: 6, dirCount: 2, clues: false },
      medium: { label: "Medium", note: "11x11 · 4 directions", size: 11, words: 8, dirCount: 4, clues: false },
      hard: { label: "Hard", note: "13x13 · clues only", size: 13, words: 10, dirCount: 8, clues: true },
    },
  },
  {
    id: "matching",
    category: "word",
    data: "terms",
    featured: true,
    title: "Matching Pairs",
    tagline: "Flip cards or link terms, dates and formulas.",
    emoji: "🃏",
    theme: "matching",
    glyphs: ["★", "♦", "●", "▲", "✦", "♥", "=", "+"],
    howTo: [
      "Flip cards: tap two cards. If a term and its match line up, they stay face up.",
      "Link terms: tap an item on the left, then its partner on the right (or drag one onto the other).",
      "Match every pair using as few moves as you can.",
    ],
    rules: [
      "Each matched pair scores 100 points.",
      "Every wrong try costs 15 points.",
      "Finish quickly for a time bonus.",
      "Choose a pack: your mock-test terms, dates & events, formulas, states & capitals, inventors, or key terms.",
    ],
    difficulty: {
      easy: { label: "Easy", note: "6 pairs", pairs: 6 },
      medium: { label: "Medium", note: "8 pairs", pairs: 8 },
      hard: { label: "Hard", note: "10 pairs", pairs: 10 },
    },
    options: [
      {
        id: "mode",
        label: "How do you want to play?",
        choices: [
          { value: "flip", label: "Flip cards" },
          { value: "link", label: "Link terms" },
        ],
        default: "flip",
      },
      {
        id: "pack",
        label: "Pack",
        choices: [
          { value: "tests", label: "From my mock tests" },
          ...Object.entries(PAIR_PACKS).map(([value, p]) => ({ value, label: p.label })),
        ],
        default: "tests",
      },
    ],
  },
  {
    id: "unscramble",
    category: "word",
    data: "terms",
    featured: false,
    title: "Unscramble",
    tagline: "Quick-fire! Put the letters back in order.",
    emoji: "🔤",
    theme: "unscramble",
    glyphs: ["✦", "✧", "?", "!", "Z", "Q", "X", "⚡"],
    howTo: [
      "A clue and a jumble of letters appear.",
      "Tap the letters in the right order - or just type the word on your keyboard.",
      "Tap a filled box (or press Backspace) to take a letter back.",
      "Beat the timer! Answer fast and in a row for bonus points.",
    ],
    rules: [
      "10 words per round. Correct answer: 100 points + up to 100 for speed.",
      "Streak bonus: +20 points for every answer in a row.",
      "Hint reveals one letter and costs 30 points. Skip scores nothing and breaks your streak.",
      "When the time runs out the word is skipped.",
    ],
    difficulty: {
      easy: { label: "Easy", note: "45 s per word", seconds: 45 },
      medium: { label: "Medium", note: "30 s per word", seconds: 30 },
      hard: { label: "Hard", note: "20 s per word", seconds: 20 },
    },
  },
  {
    id: "fillblanks",
    category: "word",
    data: "terms",
    featured: false,
    title: "Fill the Blanks",
    tagline: "Complete the concept before the bar runs out.",
    emoji: "✍️",
    theme: "fillblanks",
    glyphs: ["_", "?", "✓", "→", "⚡", "★"],
    howTo: [
      "Read the clue and complete the missing word.",
      "Easy: pick the right word from four choices.",
      "Medium and Hard: type the word. Some letters are shown to help you.",
      "The bar at the top is your timer - answer before it empties.",
    ],
    rules: [
      "10 questions per round. Correct answer: 100 points + up to 100 for speed.",
      "Streak bonus: +20 points for every answer in a row.",
      "A wrong answer or running out of time scores nothing and breaks your streak.",
    ],
    difficulty: {
      easy: { label: "Easy", note: "4 choices · 20 s", mode: "choice", seconds: 20 },
      medium: { label: "Medium", note: "type it · 20 s", mode: "type", seconds: 20, reveal: 0.4 },
      hard: { label: "Hard", note: "first letter only · 15 s", mode: "type", seconds: 15, reveal: 0 },
    },
  },
  {
    id: "blitz",
    category: "speed",
    data: "questions",
    featured: true,
    title: "Time Attack",
    tagline: "Race the clock - and the question timer keeps shrinking!",
    emoji: "⚡",
    theme: "blitz",
    glyphs: ["⚡", "⏱", "10", "5", "3", "!", "✦"],
    howTo: [
      "A big clock counts down for the whole round.",
      "Each question also has its own limit - and it shrinks by half a second after every correct answer.",
      "Pick the right option as fast as you can. Quicker answers and longer streaks score more.",
      "Wrong answers and missed questions cost you precious seconds on the main clock.",
    ],
    rules: [
      "Correct answer: 100 points + up to 100 for speed + a streak bonus (up to +100).",
      "A wrong or missed question takes seconds off the main clock (5 s on Easy, 6 s on Medium, 8 s on Hard).",
      "The per-question limit shrinks by 0.5 s per correct answer, down to a minimum.",
      "The round ends when the main clock reaches zero.",
    ],
    difficulty: {
      easy: { label: "Easy", note: "75 s · 12 s/question", total: 75, perQ: 12, minQ: 4, penalty: 5 },
      medium: { label: "Medium", note: "60 s · 10 s/question", total: 60, perQ: 10, minQ: 3, penalty: 6 },
      hard: { label: "Hard", note: "45 s · 8 s/question", total: 45, perQ: 8, minQ: 2.5, penalty: 8 },
    },
  },
  {
    id: "survival",
    category: "speed",
    data: "questions",
    featured: true,
    title: "Survival",
    tagline: "Three lives. How many questions can you survive?",
    emoji: "❤️",
    theme: "survival",
    glyphs: ["❤️", "🖤", "💔", "☠", "✚", "!"],
    howTo: [
      "You start with three hearts.",
      "Answer each question before its timer runs out.",
      "A wrong answer (or running out of time) costs a heart.",
      "Answer three in a row correctly to win a heart back.",
      "The game ends when your last heart is gone.",
    ],
    rules: [
      "Correct answer: 100 points + up to 50 for speed + a streak bonus.",
      "You can never hold more than three hearts.",
      "Clear every question in the round with at least one heart left to win.",
    ],
    difficulty: {
      easy: { label: "Easy", note: "20 s per question", seconds: 20 },
      medium: { label: "Medium", note: "15 s per question", seconds: 15 },
      hard: { label: "Hard", note: "10 s per question", seconds: 10 },
    },
  },
  {
    id: "asteroids",
    category: "speed",
    data: "questions",
    featured: true,
    title: "Asteroid Blaster",
    tagline: "Blast the asteroid with the right answer before it hits!",
    emoji: "🚀",
    theme: "asteroids",
    glyphs: ["☄️", "⭐", "✦", "🪐", "🌙", "·"],
    howTo: [
      "An asteroid falls towards your ship. A question appears below.",
      "Tap the correct answer to fire your laser and blow it up - the earlier, the more points.",
      "A wrong answer damages your shield, but you can try another option while the asteroid is still falling.",
      "If the asteroid reaches the ship it also costs a shield.",
    ],
    rules: [
      "You have 3 shields. Zero shields = game over.",
      "Direct hit: 100 points + up to 100 for shooting it early.",
      "Each destroyed asteroid makes the next one fall a little faster.",
    ],
    difficulty: {
      easy: { label: "Easy", note: "slow asteroids", fall: 18 },
      medium: { label: "Medium", note: "medium speed", fall: 13 },
      hard: { label: "Hard", note: "fast asteroids", fall: 9 },
    },
  },
  {
    id: "boardrace",
    category: "board",
    data: "questions",
    featured: true,
    title: "Board Race",
    tagline: "Move your avatar along the map and beat the computer!",
    emoji: "🏁",
    theme: "boardrace",
    glyphs: ["🏁", "🎲", "⭐", "🌳", "🚩", "👣"],
    howTo: [
      "Your avatar and the computer's robot start at the beginning of a winding board.",
      "Answer each question: a correct answer moves you forward 2 tiles - 3 if you answer within the first 40% of the time.",
      "After your move, the robot takes its turn (it only gets some questions right).",
      "⚡ tiles give a free boost, 🕳️ tiles send you back. First to the 🏁 wins!",
    ],
    rules: [
      "Wrong or missed answer: you stay where you are.",
      "Reach the finish first to win. If the questions run out, whoever is further ahead wins.",
      "Score: 40 per tile + 50 per correct answer + 500 for winning.",
      "Harder levels have a smarter, faster robot.",
    ],
    difficulty: {
      easy: { label: "Easy", note: "robot 45% · 25 s", botAccuracy: 0.45, seconds: 25 },
      medium: { label: "Medium", note: "robot 60% · 20 s", botAccuracy: 0.6, seconds: 20 },
      hard: { label: "Hard", note: "robot 78% · 15 s", botAccuracy: 0.78, seconds: 15 },
    },
    options: [
      {
        id: "avatar",
        label: "Your avatar",
        choices: ["🦊", "🐼", "🐯", "🦄", "🐸"].map((a) => ({ value: a, label: a })),
        default: "🦊",
      },
    ],
  },
  {
    id: "hangman",
    category: "word",
    data: "terms",
    featured: false,
    title: "Hangman",
    tagline: "Guess the technical term, one letter at a time.",
    emoji: "🪢",
    theme: "hangman",
    glyphs: ["A", "B", "C", "?", "_", "✎", "Z"],
    howTo: [
      "Read the clue - it describes a term from your mock tests.",
      "Tap letters (or press them on your keyboard) to guess the term.",
      "Right letters fill in the blanks. Each wrong letter adds to the drawing.",
      "Finish the word before the drawing is complete!",
    ],
    rules: [
      "6 terms per round.",
      "Solved term: 100 points + 20 for every mistake you still had left.",
      "Reveal a letter costs 30 points (you can't reveal the last letter).",
      "Easy allows 8 mistakes, Medium 6, Hard 5.",
    ],
    difficulty: {
      easy: { label: "Easy", note: "8 mistakes", lives: 8 },
      medium: { label: "Medium", note: "6 mistakes", lives: 6 },
      hard: { label: "Hard", note: "5 mistakes", lives: 5 },
    },
  },
  {
    id: "economy",
    category: "social",
    data: "questions",
    featured: true,
    title: "Quiz Market",
    tagline: "Earn coins, buy power-ups, top the leaderboard.",
    emoji: "🪙",
    theme: "economy",
    glyphs: ["🪙", "$", "💎", "🛒", "✦", "⬆"],
    howTo: [
      "Answer questions to earn coins - there is no per-question timer, only the main clock.",
      "Spend coins in the Market any time: double cash, a shield, extra time, or freeze your rivals.",
      "Three rival players earn coins on their own. Watch the live leaderboard!",
      "Finish the round with the most coins.",
    ],
    rules: [
      "Correct answer: $100 + $10 per streak step (max +$100).",
      "Wrong answer: -$50, unless you hold a shield.",
      "Double cash: next 5 correct answers pay double ($400). Shield: $250. +15 s: $300. Freeze rivals for 12 s: $500.",
      "Your final score is your coin total.",
    ],
    difficulty: {
      easy: { label: "Easy", note: "150 s · slow rivals", total: 150, botRate: 7 },
      medium: { label: "Medium", note: "120 s · average rivals", total: 120, botRate: 12 },
      hard: { label: "Hard", note: "90 s · sharp rivals", total: 90, botRate: 18 },
    },
  },
  {
    id: "livebattle",
    category: "social",
    data: "live",
    featured: true,
    title: "Live Battle",
    tagline: "Host or join a class showdown with a game PIN.",
    emoji: "📡",
    theme: "livebattle",
    glyphs: ["▲", "◆", "●", "■", "★", "?"],
    howTo: [
      "Host: choose how many questions and how long each lasts, press Create, and show the 6-digit PIN to your class.",
      "Players: open Games → Live Battle, choose Join, then type the PIN and a nickname.",
      "When everyone is in, the host presses Start. Each question appears on every screen.",
      "Tap the colour you think is right - faster correct answers score more. The leaderboard updates after every question.",
    ],
    rules: [
      "Correct answer: 500-1000 points depending on speed, plus +50 per streak step.",
      "One answer per question - no changes after you tap.",
      "Players can't join once the game has started.",
      "Questions come from the SetuLearn mock-test bank. Games are kept for a few hours, then deleted.",
    ],
    difficulty: {
      standard: { label: "Standard", note: "Kahoot-style" },
    },
    options: [
      {
        id: "role",
        label: "I want to…",
        choices: [
          { value: "join", label: "Join with a PIN" },
          { value: "host", label: "Host a game" },
        ],
        default: "join",
      },
      {
        id: "count",
        label: "Questions (host)",
        choices: [{ value: "5", label: "5" }, { value: "10", label: "10" }, { value: "15", label: "15" }, { value: "20", label: "20" }],
        default: "10",
      },
      {
        id: "seconds",
        label: "Seconds per question (host)",
        choices: [{ value: "10", label: "10 s" }, { value: "20", label: "20 s" }, { value: "30", label: "30 s" }],
        default: "20",
      },
    ],
  },
];

export const getGame = (id) => GAMES.find((g) => g.id === id);
